import{profile as p}from './profile.js';
const strings={en:{share:'Share Contact',tagline:'Your Engine. Our Commitment.',founder:'General Manager',call:'Call',save:'Save Contact',products:'Our Products',range:'Explore our lubricant range',made:'Proudly Made in Cambodia',view:'View Products →',partner:'Become a Partner',dealers:'Dealer & distribution opportunities',email:'Email',find:'Find Us',closing:'Smooth. Strong. Synergized.',wechatHelp:'Open the profile link, or scan this QR in WeChat. On the same phone, save the QR, then select it from your photos in WeChat’s scanner.',copy:'Copy WeChat ID',copied:'Copied',linkCopied:'Link copied',failed:'Could not copy. Please select and copy manually.'},km:{share:'ចែករំលែកទំនាក់ទំនង',tagline:'ម៉ាស៊ីនរបស់អ្នក។ ការប្តេជ្ញារបស់យើង។',founder:'អ្នកគ្រប់គ្រងទូទៅ',call:'ហៅទូរស័ព្ទ',save:'រក្សាទុកទំនាក់ទំនង',products:'ផលិតផលរបស់យើង',range:'ស្វែងយល់ពីប្រេងរំអិលរបស់យើង',made:'ផលិតនៅកម្ពុជាដោយមោទនភាព',view:'មើលផលិតផល →',partner:'ក្លាយជាដៃគូ',dealers:'ឱកាសសម្រាប់អ្នកលក់ និងអ្នកចែកចាយ',email:'អ៊ីមែល',find:'ស្វែងរកទីតាំងយើង',closing:'រលូន។ រឹងមាំ។ រួមកម្លាំង។',wechatHelp:'បើកតំណប្រវត្តិរូប ឬស្កេនកូដ QR ក្នុង WeChat។ នៅលើទូរស័ព្ទតែមួយ សូមរក្សាទុកកូដ QR រួចជ្រើសរើសវាពីរូបថតក្នុងកម្មវិធីស្កេន WeChat។',copy:'ចម្លង WeChat ID',copied:'បានចម្លង',linkCopied:'បានចម្លងតំណ',failed:'មិនអាចចម្លងបាន។ សូមចម្លងដោយដៃ។'},zh:{share:'分享名片',tagline:'您的引擎，我们的承诺。',founder:'总经理',call:'致电',save:'保存联系人',products:'我们的产品',range:'探索我们的润滑油系列',made:'柬埔寨制造',view:'查看产品 →',partner:'成为合作伙伴',dealers:'经销与分销合作机会',email:'电子邮箱',find:'查找我们',closing:'顺畅。强劲。协同。',wechatHelp:'打开个人资料链接，或用微信扫描此二维码。在同一部手机上，请保存二维码，然后在微信扫一扫中从相册选择它。',copy:'复制微信 ID',copied:'已复制',linkCopied:'链接已复制',failed:'无法复制，请手动复制。'}};
let lang='en';const $=id=>document.getElementById(id);function setLanguage(value){lang=strings[value]?value:'en';document.documentElement.lang=lang==='zh'?'zh-Hans':lang;$('language').value=lang;document.querySelectorAll('[data-t]').forEach(el=>el.textContent=strings[lang][el.dataset.t]);try{localStorage.setItem('language',lang)}catch{}}try{setLanguage(localStorage.getItem('language')||'en')}catch{setLanguage('en')}$('language').onchange=e=>setLanguage(e.target.value);
for(const key of ['call','telegram','products','facebook','maps','whatsapp'])$(key).href=p[key];$('email').href='mailto:'+p.email;$('wechat').querySelector('small').textContent='QR / Profile';
let timer;function notify(message){$('status').textContent=message;clearTimeout(timer);timer=setTimeout(()=>$('status').textContent='',4000)}async function copy(text,message){try{await navigator.clipboard.writeText(text);notify(message)}catch{notify(strings[lang].failed)}}
$('wechat').onclick=()=>{const dialog=$('wechat-dialog');dialog.querySelector('.phone').textContent=p.wechatId;let panel=dialog.querySelector('.wechat-options');if(!panel){panel=document.createElement('div');panel.className='wechat-options';const img=new Image();img.src=p.wechatQrImage;img.alt=p.name+' personal WeChat QR code';const open=document.createElement('a');open.className='wechat-profile-link';open.href=p.wechatUrl;open.target='_blank';open.rel='noopener noreferrer';open.dataset.wechatAction='open';const save=document.createElement('a');save.href=p.wechatQrImage;save.download=p.name.replaceAll(' ','-')+'-WeChat.png';save.dataset.wechatAction='save';panel.append(open,img,save);dialog.querySelector('h2').after(panel);}panel.querySelector('[data-wechat-action=open]').textContent=lang==='km'?'បើកប្រវត្តិរូប WeChat':lang==='zh'?'打开微信个人资料':'Open WeChat profile';panel.querySelector('[data-wechat-action=save]').textContent=lang==='km'?'រក្សាទុកកូដ QR':lang==='zh'?'保存二维码':'Save WeChat QR';dialog.showModal()};$('copy-number').onclick=()=>copy(p.wechatId,strings[lang].copied);$('wechat-dialog').addEventListener('click',e=>{if(e.target===$('wechat-dialog')){const r=e.target.getBoundingClientRect();if(e.clientY<r.top)e.target.close()}});
$('share').onclick=async()=>{const data={title:p.company,text:strings[lang].tagline,url:location.origin+'/'};if(navigator.share){try{await navigator.share(data);return}catch(e){if(e.name==='AbortError')return}}await copy(data.url,strings[lang].linkCopied)};
$('save').onclick=()=>{const card=['BEGIN:VCARD','VERSION:3.0','FN:'+p.name,'N:Chea;Sophal;;;','ORG:'+p.company,'TITLE:General Manager','TEL;TYPE=CELL:'+p.international,'EMAIL:'+p.email,'URL:'+p.products,'END:VCARD',''].join('\r\n');const url=URL.createObjectURL(new Blob([card],{type:'text/vcard;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Chea-Sophal-SYNERGIST.vcf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('wechat').onclick=()=>window.location.assign(p.wechatUrl);
$('wechat').querySelector('small').textContent='Add on WeChat';
/* WeChat: copy ID, then open the app. */
const wcText={en:{help:'Copy the ID, then open WeChat. Tap + → Add Contacts and paste the ID into search.',open:'Open WeChat',close:'Close',ready:'ID copied. Open WeChat and paste it in Add Contacts.'},km:{help:'ចម្លង ID រួចបើក WeChat។ ចុច + → Add Contacts រួចបិទភ្ជាប់ ID ដើម្បីស្វែងរក។',open:'បើក WeChat',close:'បិទ',ready:'បានចម្លង ID។ បើក WeChat រួចបិទភ្ជាប់ក្នុង Add Contacts។'},zh:{help:'复制微信 ID，然后打开微信。点击 + → 添加朋友，粘贴 ID 搜索。',open:'打开微信',close:'关闭',ready:'ID 已复制。请打开微信，在添加朋友中粘贴。'}};
$('wechat').onclick=()=>{
 const d=$('wechat-dialog'),t=wcText[lang];
 d.innerHTML='<form method="dialog"><button aria-label="'+t.close+'">×</button></form><h2>WeChat</h2><p>'+t.help+'</p><input id="wc-id" readonly aria-label="WeChat ID" style="width:100%;padding:12px;color:#08162b;background:#fff;border-radius:6px"><div class="wechat-options"><button id="wc-copy" type="button">'+strings[lang].copy+'</button><a class="wechat-profile-link" href="weixin://">'+t.open+'</a></div><p id="wc-feedback" role="status" aria-live="polite"></p>';
 d.querySelector('#wc-id').value=p.wechatId;
 d.querySelector('#wc-copy').onclick=async()=>{try{await navigator.clipboard.writeText(p.wechatId);d.querySelector('#wc-feedback').textContent=t.ready}catch{d.querySelector('#wc-feedback').textContent=strings[lang].failed;d.querySelector('#wc-id').select()}};
 d.showModal();
};

/* Optional uppercase name preview; normal links retain title case. */
document.querySelector('.identity h1').textContent=new URLSearchParams(location.search).get('preview')==='uppercase'?p.name.toUpperCase():p.name;
document.title=p.name+' · SYNERGIST LUBRICANTS';
